### PR TITLE
Using `notebook` CMD to run the jupyter stack

### PR DESCRIPTION
**Pull request by unkcpz**
The new `jupyter/minimal-notebook` image uses `lab` CMD to run the jupyter server, which was introduced by https://github.com/jupyter/docker-stacks/pull/1575. It provide `DOCKER_STACKS_JUPYTER_CMD` to set how to run it.
The lab (full-stack) is for AiiDAlab only and should start with notebook mode. I pin it as an environment variable to start the jupyter backend.
Since we have the new jupyterhub, the `NOTEBOOK_ARGS` can be used to set the notebook arguments.

### CODE REVIEW

**Comment by danielhollas** [comment]
I tried to give it a test, but I am getting a 500 Jupyter server error, due to this jinja exception

```
      File "/opt/conda/lib/python3.9/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/opt/conda/lib/python3.9/site-packages/nbconvert/exporters/__init__.py", line 3, in <module>
        from .html import HTMLExporter
      File "/opt/conda/lib/python3.9/site-packages/nbconvert/exporters/html.py", line 12, in <module>
        from jinja2 import contextfilter
    ImportError: cannot import name 'contextfilter' from 'jinja2' (/opt/conda/lib/python3.9/site-packages/jinja2/__init__.py)
```

This is probably another side-effect of updating the base image to Python 9.13? Perhaps we need to adjust the nbconvert / jinja dependencies, not sure where they are defined. 

https://github.com/d2l-ai/d2l-book/issues/46

**Comment by danielhollas** [comment]
Ah, I see the error comes from AWB which reinstalls some dependencies and breaks the environment, which you're already trying to address in https://github.com/aiidalab/aiidalab-widgets-base/pull/395

If I don't install AWB, things seems to work.

File: stack/lab/Dockerfile [hunk 1]
```diff
@@ -3,6 +3,13 @@ FROM base
 
 LABEL maintainer="AiiDAlab Team <aiidalab@materialscloud.org>"
 
+# The lab mode is default to run jupyter server.
```
Comment (danielhollas) [inline stack/lab/Dockerfile:6]:
```suggestion
# By default, Jupyter Docker image launches the JupyterLab interface.
# Here, we change it to the classic Jupyter Notebook which is used by AiiDAlab.
# In the future, we might want to switch to other options such as 'nbclassic' or 'retro', see:
# https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#switching-back-to-the-classic-notebook-or-using-a-different-startup-command
```

File: stack/lab/Dockerfile [hunk 2]
```diff
@@ -3,6 +3,13 @@ FROM base
...
+# Here the CMD pinned to `notebook` for running in legacy notebook backend
+# In the future, we have appmode compatible with nbclassic
```
Comment (danielhollas) [inline stack/lab/Dockerfile:8]: Do I understand correctly that Appmode is currently not compatible with the `nbclassic` option?

**Review by danielhollas — APPROVED** [review]
I have verified that the issue exist on the current `aiidalab/full-stack:edge` and verified that this PR fixes it.

File: stack/lab/Dockerfile (hunk 1 above)
Comment (unkcpz) [reply stack/lab/Dockerfile]: Thanks! changed.

**Comment by unkcpz** [comment]
> Ah, I see the error comes from AWB which reinstalls some dependencies and breaks the environment, which you're already trying to address in https://github.com/aiidalab/aiidalab-widgets-base/pull/395

Yes, exactly! @danielhollas thanks a lot for the review. I addressed the things you mentioned.
